apiVersion: v1
kind: Secret
metadata:
  name: cityflow-secrets
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  GRAFANA_ADMIN_USER: {{ .Values.secrets.grafanaAdminUser | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
