global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: cityflow-collector
    static_configs:
      - targets:
          - collector:8080

  - job_name: cityflow-predictor
    static_configs:
      - targets:
          - predictor:8080

  - job_name: cityflow-rerouter
    static_configs:
      - targets:
          - rerouter:8080

  - job_name: redis
    static_configs:
      - targets:
          - redis-exporter:9121

  - job_name: mosquitto
    static_configs:
      - targets:
          - mosquitto-exporter:9234
