apiVersion: v1
kind: Secret
metadata:
  name: cityflow-secrets
  namespace: cityflow
type: Opaque
stringData:
  POSTGRES_DB: cityflow
  POSTGRES_USER: cityflow
  POSTGRES_PASSWORD: cityflow_dev_password
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin
